# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractSpinBox, QApplication, QFormLayout,
    QFrame, QGraphicsView, QGridLayout, QHBoxLayout,
    QHeaderView, QLabel, QLayout, QListView,
    QMainWindow, QMenu, QMenuBar, QProgressBar,
    QPushButton, QRadioButton, QSizePolicy, QSlider,
    QSpinBox, QStatusBar, QTextEdit, QWidget)

from widgets import (FilmStripWidget, ProjectBinWidget, SceneTableWidget)

class Ui_mainWindow_Qhawana(object):
    def setupUi(self, mainWindow_Qhawana):
        if not mainWindow_Qhawana.objectName():
            mainWindow_Qhawana.setObjectName(u"mainWindow_Qhawana")
        mainWindow_Qhawana.resize(1259, 969)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow_Qhawana.sizePolicy().hasHeightForWidth())
        mainWindow_Qhawana.setSizePolicy(sizePolicy)
        mainWindow_Qhawana.setMinimumSize(QSize(640, 480))
        self.actionQuit = QAction(mainWindow_Qhawana)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionNew = QAction(mainWindow_Qhawana)
        self.actionNew.setObjectName(u"actionNew")
        self.actionOpen = QAction(mainWindow_Qhawana)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(mainWindow_Qhawana)
        self.actionSave.setObjectName(u"actionSave")
        self.actions = QAction(mainWindow_Qhawana)
        self.actions.setObjectName(u"actions")
        self.actionSave_as = QAction(mainWindow_Qhawana)
        self.actionSave_as.setObjectName(u"actionSave_as")
        self.actionSave_As = QAction(mainWindow_Qhawana)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionAbout_Qhawana = QAction(mainWindow_Qhawana)
        self.actionAbout_Qhawana.setObjectName(u"actionAbout_Qhawana")
        self.actionPreferences = QAction(mainWindow_Qhawana)
        self.actionPreferences.setObjectName(u"actionPreferences")
        self.centralwidget = QWidget(mainWindow_Qhawana)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QSize(640, 480))
        self.centralwidget.setMaximumSize(QSize(4096, 4096))
        self.centralwidget.setBaseSize(QSize(1024, 768))
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.gridLayout = QGridLayout()
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.textEdit_mediaSourceDirectory = QTextEdit(self.centralwidget)
        self.textEdit_mediaSourceDirectory.setObjectName(u"textEdit_mediaSourceDirectory")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.textEdit_mediaSourceDirectory.sizePolicy().hasHeightForWidth())
        self.textEdit_mediaSourceDirectory.setSizePolicy(sizePolicy1)
        self.textEdit_mediaSourceDirectory.setMaximumSize(QSize(16777215, 25))
        self.textEdit_mediaSourceDirectory.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textEdit_mediaSourceDirectory.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textEdit_mediaSourceDirectory.setReadOnly(True)

        self.gridLayout.addWidget(self.textEdit_mediaSourceDirectory, 1, 1, 1, 2)

        self.pushButton_startShow = QPushButton(self.centralwidget)
        self.pushButton_startShow.setObjectName(u"pushButton_startShow")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.pushButton_startShow.sizePolicy().hasHeightForWidth())
        self.pushButton_startShow.setSizePolicy(sizePolicy2)

        self.gridLayout.addWidget(self.pushButton_startShow, 9, 6, 1, 2)

        self.frame_settings = QFrame(self.centralwidget)
        self.frame_settings.setObjectName(u"frame_settings")
        sizePolicy.setHeightForWidth(self.frame_settings.sizePolicy().hasHeightForWidth())
        self.frame_settings.setSizePolicy(sizePolicy)
        self.frame_settings.setMinimumSize(QSize(0, 0))
        self.frame_settings.setMaximumSize(QSize(250, 16777215))
        self.frame_settings.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_settings.setFrameShadow(QFrame.Shadow.Raised)
        self.formLayout = QFormLayout(self.frame_settings)
        self.formLayout.setObjectName(u"formLayout")
        self.label_transitionTime = QLabel(self.frame_settings)
        self.label_transitionTime.setObjectName(u"label_transitionTime")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.label_transitionTime.sizePolicy().hasHeightForWidth())
        self.label_transitionTime.setSizePolicy(sizePolicy3)

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.label_transitionTime)

        self.label_defaultDelay = QLabel(self.frame_settings)
        self.label_defaultDelay.setObjectName(u"label_defaultDelay")
        sizePolicy3.setHeightForWidth(self.label_defaultDelay.sizePolicy().hasHeightForWidth())
        self.label_defaultDelay.setSizePolicy(sizePolicy3)

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.label_defaultDelay)

        self.spinBox_transitionTime = QSpinBox(self.frame_settings)
        self.spinBox_transitionTime.setObjectName(u"spinBox_transitionTime")
        sizePolicy2.setHeightForWidth(self.spinBox_transitionTime.sizePolicy().hasHeightForWidth())
        self.spinBox_transitionTime.setSizePolicy(sizePolicy2)
        self.spinBox_transitionTime.setMinimumSize(QSize(80, 0))
        self.spinBox_transitionTime.setMaximumSize(QSize(100, 16777215))
        self.spinBox_transitionTime.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.spinBox_transitionTime.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.spinBox_transitionTime.setMinimum(1)
        self.spinBox_transitionTime.setMaximum(3600000)
        self.spinBox_transitionTime.setSingleStep(100)
        self.spinBox_transitionTime.setValue(1000)

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.spinBox_transitionTime)

        self.spinBox_defaultDelay = QSpinBox(self.frame_settings)
        self.spinBox_defaultDelay.setObjectName(u"spinBox_defaultDelay")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.spinBox_defaultDelay.sizePolicy().hasHeightForWidth())
        self.spinBox_defaultDelay.setSizePolicy(sizePolicy4)
        self.spinBox_defaultDelay.setMinimumSize(QSize(80, 0))
        self.spinBox_defaultDelay.setMaximumSize(QSize(100, 16777215))
        self.spinBox_defaultDelay.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.spinBox_defaultDelay.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.spinBox_defaultDelay.setMinimum(1)
        self.spinBox_defaultDelay.setMaximum(3600000)
        self.spinBox_defaultDelay.setSingleStep(100)
        self.spinBox_defaultDelay.setValue(5000)

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.spinBox_defaultDelay)

        self.label_settingsHeader = QLabel(self.frame_settings)
        self.label_settingsHeader.setObjectName(u"label_settingsHeader")

        self.formLayout.setWidget(0, QFormLayout.SpanningRole, self.label_settingsHeader)


        self.gridLayout.addWidget(self.frame_settings, 6, 6, 1, 1)

        self.label_applicationName = QLabel(self.centralwidget)
        self.label_applicationName.setObjectName(u"label_applicationName")
        self.label_applicationName.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label_applicationName, 0, 1, 1, 1)

        self.label_mediaSourceDirectory = QLabel(self.centralwidget)
        self.label_mediaSourceDirectory.setObjectName(u"label_mediaSourceDirectory")

        self.gridLayout.addWidget(self.label_mediaSourceDirectory, 1, 0, 1, 1)

        self.treeView = ProjectBinWidget(self.centralwidget)
        self.treeView.setObjectName(u"treeView")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(3)
        sizePolicy5.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy5)
        self.treeView.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.treeView.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.treeView.setProperty(u"showDropIndicator", False)
        self.treeView.setDragEnabled(True)
        self.treeView.setDragDropMode(QAbstractItemView.DragDropMode.DragDrop)

        self.gridLayout.addWidget(self.treeView, 7, 3, 1, 5)

        self.pushButton_playPausePreview = QPushButton(self.centralwidget)
        self.pushButton_playPausePreview.setObjectName(u"pushButton_playPausePreview")
        self.pushButton_playPausePreview.setEnabled(False)
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.pushButton_playPausePreview.sizePolicy().hasHeightForWidth())
        self.pushButton_playPausePreview.setSizePolicy(sizePolicy6)
        self.pushButton_playPausePreview.setMaximumSize(QSize(30, 30))
        self.pushButton_playPausePreview.setText(u"")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaPlaybackStart))
        self.pushButton_playPausePreview.setIcon(icon)
        self.pushButton_playPausePreview.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_playPausePreview, 4, 4, 1, 1)

        self.pushButton_inPoint = QPushButton(self.centralwidget)
        self.pushButton_inPoint.setObjectName(u"pushButton_inPoint")
        self.pushButton_inPoint.setEnabled(False)
        sizePolicy6.setHeightForWidth(self.pushButton_inPoint.sizePolicy().hasHeightForWidth())
        self.pushButton_inPoint.setSizePolicy(sizePolicy6)
        self.pushButton_inPoint.setMaximumSize(QSize(30, 30))

        self.gridLayout.addWidget(self.pushButton_inPoint, 4, 3, 1, 1)

        self.pushButton_mediaSourceDirectory = QPushButton(self.centralwidget)
        self.pushButton_mediaSourceDirectory.setObjectName(u"pushButton_mediaSourceDirectory")
        sizePolicy6.setHeightForWidth(self.pushButton_mediaSourceDirectory.sizePolicy().hasHeightForWidth())
        self.pushButton_mediaSourceDirectory.setSizePolicy(sizePolicy6)

        self.gridLayout.addWidget(self.pushButton_mediaSourceDirectory, 2, 2, 1, 1)

        self.horizontalSlider_videoPosition = QSlider(self.centralwidget)
        self.horizontalSlider_videoPosition.setObjectName(u"horizontalSlider_videoPosition")
        self.horizontalSlider_videoPosition.setEnabled(False)
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
        sizePolicy7.setHorizontalStretch(5)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.horizontalSlider_videoPosition.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_videoPosition.setSizePolicy(sizePolicy7)
        self.horizontalSlider_videoPosition.setMaximum(100)
        self.horizontalSlider_videoPosition.setOrientation(Qt.Orientation.Horizontal)
        self.horizontalSlider_videoPosition.setInvertedControls(False)
        self.horizontalSlider_videoPosition.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.horizontalSlider_videoPosition.setTickInterval(10)

        self.gridLayout.addWidget(self.horizontalSlider_videoPosition, 4, 5, 1, 2)

        self.label_applicationIcon = QLabel(self.centralwidget)
        self.label_applicationIcon.setObjectName(u"label_applicationIcon")
        sizePolicy8 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy8.setHorizontalStretch(0)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.label_applicationIcon.sizePolicy().hasHeightForWidth())
        self.label_applicationIcon.setSizePolicy(sizePolicy8)
        self.label_applicationIcon.setMinimumSize(QSize(96, 96))
        self.label_applicationIcon.setMaximumSize(QSize(96, 96))

        self.gridLayout.addWidget(self.label_applicationIcon, 0, 0, 1, 1)

        self.radioButton_changes = QRadioButton(self.centralwidget)
        self.radioButton_changes.setObjectName(u"radioButton_changes")
        self.radioButton_changes.setEnabled(False)

        self.gridLayout.addWidget(self.radioButton_changes, 0, 2, 1, 1)

        self.listView_filmStrip = FilmStripWidget(self.centralwidget)
        self.listView_filmStrip.setObjectName(u"listView_filmStrip")
        sizePolicy1.setHeightForWidth(self.listView_filmStrip.sizePolicy().hasHeightForWidth())
        self.listView_filmStrip.setSizePolicy(sizePolicy1)
        self.listView_filmStrip.setMinimumSize(QSize(800, 120))
        self.listView_filmStrip.setMaximumSize(QSize(16777215, 120))
        self.listView_filmStrip.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listView_filmStrip.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.listView_filmStrip.setAutoScroll(True)
        self.listView_filmStrip.setProperty(u"showDropIndicator", True)
        self.listView_filmStrip.setDragDropMode(QAbstractItemView.DragDropMode.InternalMove)
        self.listView_filmStrip.setSelectionMode(QAbstractItemView.SelectionMode.ContiguousSelection)
        self.listView_filmStrip.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.listView_filmStrip.setIconSize(QSize(100, 100))
        self.listView_filmStrip.setMovement(QListView.Movement.Snap)
        self.listView_filmStrip.setFlow(QListView.Flow.LeftToRight)
        self.listView_filmStrip.setProperty(u"isWrapping", False)
        self.listView_filmStrip.setSpacing(15)
        self.listView_filmStrip.setGridSize(QSize(100, 100))
        self.listView_filmStrip.setViewMode(QListView.ViewMode.IconMode)
        self.listView_filmStrip.setUniformItemSizes(True)

        self.gridLayout.addWidget(self.listView_filmStrip, 8, 0, 1, 8)

        self.textEdit_notes = QTextEdit(self.centralwidget)
        self.textEdit_notes.setObjectName(u"textEdit_notes")
        sizePolicy9 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy9.setHorizontalStretch(0)
        sizePolicy9.setVerticalStretch(1)
        sizePolicy9.setHeightForWidth(self.textEdit_notes.sizePolicy().hasHeightForWidth())
        self.textEdit_notes.setSizePolicy(sizePolicy9)
        self.textEdit_notes.setMinimumSize(QSize(200, 0))
        self.textEdit_notes.setBaseSize(QSize(0, 150))
        self.textEdit_notes.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)

        self.gridLayout.addWidget(self.textEdit_notes, 6, 3, 1, 3)

        self.pushButton_outPoint = QPushButton(self.centralwidget)
        self.pushButton_outPoint.setObjectName(u"pushButton_outPoint")
        self.pushButton_outPoint.setEnabled(False)
        sizePolicy2.setHeightForWidth(self.pushButton_outPoint.sizePolicy().hasHeightForWidth())
        self.pushButton_outPoint.setSizePolicy(sizePolicy2)
        self.pushButton_outPoint.setMaximumSize(QSize(30, 30))
        self.pushButton_outPoint.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

        self.gridLayout.addWidget(self.pushButton_outPoint, 4, 7, 1, 1)

        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setEnabled(False)
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(False)

        self.gridLayout.addWidget(self.progressBar, 9, 0, 1, 3)

        self.graphicsView_preview = QGraphicsView(self.centralwidget)
        self.graphicsView_preview.setObjectName(u"graphicsView_preview")
        sizePolicy10 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy10.setHorizontalStretch(1)
        sizePolicy10.setVerticalStretch(2)
        sizePolicy10.setHeightForWidth(self.graphicsView_preview.sizePolicy().hasHeightForWidth())
        self.graphicsView_preview.setSizePolicy(sizePolicy10)
        self.graphicsView_preview.setMinimumSize(QSize(640, 0))
        self.graphicsView_preview.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.graphicsView_preview.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)

        self.gridLayout.addWidget(self.graphicsView_preview, 0, 3, 4, 5)

        self.tableView_scenes = SceneTableWidget(self.centralwidget)
        self.tableView_scenes.setObjectName(u"tableView_scenes")
        sizePolicy11 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy11.setHorizontalStretch(4)
        sizePolicy11.setVerticalStretch(0)
        sizePolicy11.setHeightForWidth(self.tableView_scenes.sizePolicy().hasHeightForWidth())
        self.tableView_scenes.setSizePolicy(sizePolicy11)
        self.tableView_scenes.setAcceptDrops(True)
        self.tableView_scenes.setProperty(u"showDropIndicator", True)
        self.tableView_scenes.setDragDropOverwriteMode(False)
        self.tableView_scenes.setDragDropMode(QAbstractItemView.DragDropMode.DragDrop)
        self.tableView_scenes.setDefaultDropAction(Qt.DropAction.MoveAction)
        self.tableView_scenes.setAlternatingRowColors(True)
        self.tableView_scenes.setSelectionMode(QAbstractItemView.SelectionMode.ContiguousSelection)
        self.tableView_scenes.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)

        self.gridLayout.addWidget(self.tableView_scenes, 3, 0, 5, 3)


        self.horizontalLayout.addLayout(self.gridLayout)

        mainWindow_Qhawana.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(mainWindow_Qhawana)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1259, 22))
        self.menupyMultiVision = QMenu(self.menubar)
        self.menupyMultiVision.setObjectName(u"menupyMultiVision")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        mainWindow_Qhawana.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(mainWindow_Qhawana)
        self.statusbar.setObjectName(u"statusbar")
        mainWindow_Qhawana.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menupyMultiVision.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menupyMultiVision.addSeparator()
        self.menupyMultiVision.addSeparator()
        self.menupyMultiVision.addAction(self.actionNew)
        self.menupyMultiVision.addAction(self.actionOpen)
        self.menupyMultiVision.addSeparator()
        self.menupyMultiVision.addAction(self.actionSave)
        self.menupyMultiVision.addAction(self.actionSave_As)
        self.menupyMultiVision.addSeparator()
        self.menupyMultiVision.addAction(self.actionQuit)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout_Qhawana)

        self.retranslateUi(mainWindow_Qhawana)

        QMetaObject.connectSlotsByName(mainWindow_Qhawana)
    # setupUi

    def retranslateUi(self, mainWindow_Qhawana):
        mainWindow_Qhawana.setWindowTitle(QCoreApplication.translate("mainWindow_Qhawana", u"Qhawana", None))
        self.actionQuit.setText(QCoreApplication.translate("mainWindow_Qhawana", u"Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("mainWindow_Qhawana", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew.setText(QCoreApplication.translate("mainWindow_Qhawana", u"New...", None))
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("mainWindow_Qhawana", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen.setText(QCoreApplication.translate("mainWindow_Qhawana", u"Open...", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("mainWindow_Qhawana", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("mainWindow_Qhawana", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("mainWindow_Qhawana", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actions.setText(QCoreApplication.translate("mainWindow_Qhawana", u"s", None))
        self.actionSave_as.setText(QCoreApplication.translate("mainWindow_Qhawana", u"Save as...", None))
        self.actionSave_As.setText(QCoreApplication.translate("mainWindow_Qhawana", u"Save As...", None))
        self.actionAbout_Qhawana.setText(QCoreApplication.translate("mainWindow_Qhawana", u"About Qhawana", None))
        self.actionPreferences.setText(QCoreApplication.translate("mainWindow_Qhawana", u"Preferences...", None))
        self.textEdit_mediaSourceDirectory.setPlaceholderText(QCoreApplication.translate("mainWindow_Qhawana", u"(select)", None))
        self.pushButton_startShow.setText(QCoreApplication.translate("mainWindow_Qhawana", u"Open presenter view...", None))
        self.label_transitionTime.setText(QCoreApplication.translate("mainWindow_Qhawana", u"Transition time:", None))
        self.label_defaultDelay.setText(QCoreApplication.translate("mainWindow_Qhawana", u"Default delay:", None))
        self.spinBox_transitionTime.setSuffix(QCoreApplication.translate("mainWindow_Qhawana", u" ms", None))
        self.spinBox_defaultDelay.setSuffix(QCoreApplication.translate("mainWindow_Qhawana", u" ms", None))
        self.label_settingsHeader.setText(QCoreApplication.translate("mainWindow_Qhawana", u"Multi Vision Show settings:", None))
        self.label_applicationName.setText(QCoreApplication.translate("mainWindow_Qhawana", u"Qhawana", None))
        self.label_mediaSourceDirectory.setText(QCoreApplication.translate("mainWindow_Qhawana", u"Media source directory:", None))
        self.pushButton_inPoint.setText(QCoreApplication.translate("mainWindow_Qhawana", u"In", None))
        self.pushButton_mediaSourceDirectory.setText(QCoreApplication.translate("mainWindow_Qhawana", u"browse...", None))
        self.label_applicationIcon.setText("")
        self.radioButton_changes.setText(QCoreApplication.translate("mainWindow_Qhawana", u"Changes", None))
        self.textEdit_notes.setPlaceholderText(QCoreApplication.translate("mainWindow_Qhawana", u"Notes", None))
        self.pushButton_outPoint.setText(QCoreApplication.translate("mainWindow_Qhawana", u"Out", None))
        self.menupyMultiVision.setTitle(QCoreApplication.translate("mainWindow_Qhawana", u"File", None))
        self.menuSettings.setTitle(QCoreApplication.translate("mainWindow_Qhawana", u"Settings", None))
        self.menuHelp.setTitle(QCoreApplication.translate("mainWindow_Qhawana", u"Help", None))
    # retranslateUi

