# Form implementation generated from reading ui file 'ui_multiVisionShow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form_multiVisionShow(object):
    def setupUi(self, Form_multiVisionShow):
        Form_multiVisionShow.setObjectName("Form_multiVisionShow")
        Form_multiVisionShow.resize(1081, 786)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_multiVisionShow.sizePolicy().hasHeightForWidth())
        Form_multiVisionShow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        Form_multiVisionShow.setPalette(palette)
        Form_multiVisionShow.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        Form_multiVisionShow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        Form_multiVisionShow.setWindowTitle("")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form_multiVisionShow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(27, 20, 1041, 751))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(640, 480))
        self.graphicsView.setAcceptDrops(False)
        self.graphicsView.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        self.graphicsView.setBackgroundBrush(brush)
        self.graphicsView.setInteractive(False)
        self.graphicsView.setRenderHints(QtGui.QPainter.RenderHint.Antialiasing|QtGui.QPainter.RenderHint.LosslessImageRendering|QtGui.QPainter.RenderHint.SmoothPixmapTransform|QtGui.QPainter.RenderHint.TextAntialiasing)
        self.graphicsView.setTransformationAnchor(QtWidgets.QGraphicsView.ViewportAnchor.NoAnchor)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)

        self.retranslateUi(Form_multiVisionShow)
        QtCore.QMetaObject.connectSlotsByName(Form_multiVisionShow)

    def retranslateUi(self, Form_multiVisionShow):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_multiVisionShow = QtWidgets.QWidget()
    ui = Ui_Form_multiVisionShow()
    ui.setupUi(Form_multiVisionShow)
    Form_multiVisionShow.show()
    sys.exit(app.exec())
