# Form implementation generated from reading ui file 'ui_multiVisionShow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_multiVisionShow(object):
    def setupUi(self, Form_multiVisionShow):
        Form_multiVisionShow.setObjectName("Form_multiVisionShow")
        Form_multiVisionShow.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_multiVisionShow.sizePolicy().hasHeightForWidth())
        Form_multiVisionShow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        Form_multiVisionShow.setPalette(palette)
        Form_multiVisionShow.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        Form_multiVisionShow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        Form_multiVisionShow.setWindowTitle("")
        self.label_image = QtWidgets.QLabel(parent=Form_multiVisionShow)
        self.label_image.setGeometry(QtCore.QRect(10, 10, 191, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.label_image.setAutoFillBackground(False)
        self.label_image.setText("")
        self.label_image.setScaledContents(False)
        self.label_image.setObjectName("label_image")
        self.videoWidget = QVideoWidget(parent=Form_multiVisionShow)
        self.videoWidget.setGeometry(QtCore.QRect(219, 10, 171, 161))
        self.videoWidget.setAutoFillBackground(False)
        self.videoWidget.setObjectName("videoWidget")

        self.retranslateUi(Form_multiVisionShow)
        QtCore.QMetaObject.connectSlotsByName(Form_multiVisionShow)

    def retranslateUi(self, Form_multiVisionShow):
        pass
from PyQt6.QtMultimediaWidgets import QVideoWidget
